title: "🚀 run $command"
description: "Easily get / test the output of shell commands"
theme: jekyll-theme-merlot
markdown: kramdown
show_downloads: true
twitter_username: rebeccca_taylor
github_username: beccasaurus

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github:
  zip_url: https://github.com/specs-sh/run.sh/archive/v1.1.0.zip
  tar_url: https://github.com/specs-sh/run.sh/archive/v1.1.0.tar.gz
  owner_url: https://github.com/beccasaurus
  owner_name: "@beccasaurus"

defaults:
  -
    values:
      layout: default

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock