name: Mac (BASH 3.2)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: "bash --version | head -1"
        shell: bash
      - run: "./vendor/microspec spec/*.spec.sh"
        shell: bash
        env:
          VERBOSE: true